name: TauriWidgetExtension

options:
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  TauriWidgets:
    path: /Users/laeglaur/Documents/code/notebook/node_modules/.pnpm/tauri-plugin-widgets-api@0.3.0/node_modules/tauri-plugin-widgets-api/swift

targets:
  TauriWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: folia Block
        CFBundleShortVersionString: "1.2"
        CFBundleVersion: "4"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.laeglaur.notebook.widgetkit
        PRODUCT_NAME: TauriWidgetExtension
        SWIFT_VERSION: "5.9"
        CODE_SIGN_ENTITLEMENTS: TauriWidgetExtension.entitlements
        MARKETING_VERSION: "1.2"
        CURRENT_PROJECT_VERSION: "4"
        SKIP_INSTALL: YES
    dependencies:
      - package: TauriWidgets
